project_id = "akkbfzfjappludgsrwsw"

[functions.verify-password]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.ticto-webhook]
verify_jwt = false

[functions.redeem-coupon]
verify_jwt = false
 
 [functions.ai-assistant]
 verify_jwt = false