import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";

export interface Podcast {
  id: string;
  space_id: string | null;
  author_id: string | null;
  title: string;
  slug: string;
  description: string | null;
  audio_url: string;
  cover_url: string | null;
  duration_seconds: number | null;
  tags: string[];
  is_published: boolean;
  published_at: string | null;
  created_at: string;
  updated_at: string;
  spaces?: {
    id: string;
    name: string;
    slug: string;
    icon: string | null;
  } | null;
}

export function usePodcasts(spaceId?: string | null) {
  return useQuery({
    queryKey: ["podcasts", spaceId],
    queryFn: async () => {
      let query = supabase
        .from("podcasts")
        .select(`
          *,
          spaces(id, name, slug, icon)
        `)
        .eq("is_published", true)
        .order("published_at", { ascending: false });

      if (spaceId) {
        query = query.eq("space_id", spaceId);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as Podcast[];
    },
  });
}

export function useAdminPodcasts() {
  return useQuery({
    queryKey: ["admin-podcasts"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("podcasts")
        .select(`
          *,
          spaces(id, name, slug, icon)
        `)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data as Podcast[];
    },
  });
}

export function usePodcast(podcastId: string) {
  return useQuery({
    queryKey: ["podcast", podcastId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("podcasts")
        .select(`
          *,
          spaces(id, name, slug, icon)
        `)
        .eq("id", podcastId)
        .single();

      if (error) throw error;
      return data as Podcast;
    },
    enabled: !!podcastId,
  });
}

// Buscar podcast por slug (SEO-friendly URLs)
export function usePodcastBySlug(podcastSlug: string | undefined) {
  return useQuery({
    queryKey: ["podcast-by-slug", podcastSlug],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("podcasts")
        .select(`
          *,
          spaces(id, name, slug, icon)
        `)
        .eq("slug", podcastSlug)
        .eq("is_published", true)
        .single();

      if (error) return null;
      return data as Podcast;
    },
    enabled: !!podcastSlug,
  });
}

export interface CreatePodcastInput {
  space_id?: string | null;
  title: string;
  description?: string | null;
  audio_url: string;
  cover_url?: string | null;
  duration_seconds?: number | null;
  tags?: string[];
  is_published?: boolean;
  published_at?: string | null;
}

export function useCreatePodcast() {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async (input: CreatePodcastInput) => {
      // slug is auto-generated by database trigger
      const { data, error } = await supabase
        .from("podcasts")
        .insert({
          ...input,
          author_id: user?.id,
          tags: input.tags || [],
        } as any)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["podcasts"] });
      queryClient.invalidateQueries({ queryKey: ["admin-podcasts"] });
      toast.success("Podcast criado com sucesso!");
    },
    onError: (error) => {
      console.error("Error creating podcast:", error);
      toast.error("Erro ao criar podcast");
    },
  });
}

export function useUpdatePodcast() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, ...input }: CreatePodcastInput & { id: string }) => {
      const { data, error } = await supabase
        .from("podcasts")
        .update(input)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["podcasts"] });
      queryClient.invalidateQueries({ queryKey: ["admin-podcasts"] });
      queryClient.invalidateQueries({ queryKey: ["podcast", variables.id] });
      toast.success("Podcast atualizado com sucesso!");
    },
    onError: (error) => {
      console.error("Error updating podcast:", error);
      toast.error("Erro ao atualizar podcast");
    },
  });
}

export function useDeletePodcast() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (podcastId: string) => {
      const { error } = await supabase
        .from("podcasts")
        .delete()
        .eq("id", podcastId);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["podcasts"] });
      queryClient.invalidateQueries({ queryKey: ["admin-podcasts"] });
      toast.success("Podcast excluído com sucesso!");
    },
    onError: (error) => {
      console.error("Error deleting podcast:", error);
      toast.error("Erro ao excluir podcast");
    },
  });
}

// ============ ENGAGEMENT HOOKS ============

export function useLikePodcast() {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async ({ podcastId, isLiked }: { podcastId: string; isLiked: boolean }) => {
      if (!user) throw new Error("User not authenticated");

      if (isLiked) {
        const { error } = await supabase
          .from("podcast_likes")
          .delete()
          .eq("podcast_id", podcastId)
          .eq("user_id", user.id);
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from("podcast_likes")
          .insert({ podcast_id: podcastId, user_id: user.id });
        if (error) throw error;
      }
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["podcasts"] });
      queryClient.invalidateQueries({ queryKey: ["podcast", variables.podcastId] });
    },
    onError: (error) => {
      console.error("Error toggling podcast like:", error);
    },
  });
}

export function useSavePodcast() {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async ({ podcastId, isSaved }: { podcastId: string; isSaved: boolean }) => {
      if (!user) throw new Error("User not authenticated");

      if (isSaved) {
        const { error } = await supabase
          .from("saved_podcasts")
          .delete()
          .eq("podcast_id", podcastId)
          .eq("user_id", user.id);
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from("saved_podcasts")
          .insert({ podcast_id: podcastId, user_id: user.id });
        if (error) throw error;
      }
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["podcasts"] });
      queryClient.invalidateQueries({ queryKey: ["podcast", variables.podcastId] });
      queryClient.invalidateQueries({ queryKey: ["saved-podcasts"] });
    },
    onError: (error) => {
      console.error("Error toggling podcast save:", error);
    },
  });
}

export function useAddPodcastComment() {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async ({ podcastId, content, parentId }: { podcastId: string; content: string; parentId?: string }) => {
      if (!user) throw new Error("User not authenticated");

      const { data, error } = await supabase
        .from("podcast_comments")
        .insert({
          podcast_id: podcastId,
          user_id: user.id,
          content,
          parent_id: parentId || null,
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["podcast", variables.podcastId] });
      queryClient.invalidateQueries({ queryKey: ["podcast-comments", variables.podcastId] });
    },
    onError: (error) => {
      console.error("Error adding podcast comment:", error);
    },
  });
}

export function useLikePodcastComment() {
  const { user } = useAuth();

  return useMutation({
    mutationFn: async ({ commentId, isLiked }: { commentId: string; isLiked: boolean }) => {
      if (!user) throw new Error("User not authenticated");

      if (isLiked) {
        const { error } = await supabase
          .from("podcast_comment_likes")
          .delete()
          .eq("comment_id", commentId)
          .eq("user_id", user.id);
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from("podcast_comment_likes")
          .insert({ comment_id: commentId, user_id: user.id });
        if (error) throw error;
      }
    },
    onError: (error) => {
      console.error("Error toggling comment like:", error);
    },
  });
}

export function formatDuration(seconds: number | null): string {
  if (!seconds) return "0 min";
  
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);

  if (hours > 0) {
    return `${hours}h ${minutes}min`;
  }
  return `${minutes} min`;
}
